### ISSUE TITLE
GUI & windows binary

### ISSUE THREAD

**Issue by phlummox** [mlda065/Pandora-Export#1]
Hi -

I've added a Tkinter gui (https://github.com/phlummox/Pandora-Export/blob/master/export_gui.py), which may be more convenient for non-programmers to use. (Should also be possible to freeze the whole thing into a Windows binary, too, which I've tried to do using `pyinstaller`, but I haven't had a windows machine available to test it on.)
  &nbsp; Anyway, the GUI code's yours if you want it, else I hope you don't mind me forking.

**Comment by mdavis-xyz** [comment]
Wow, great!

I'll give that a try when I get home. If it works, I'll add it into my repo. (Best to keep it all in the one place)

**Comment by phlummox** [comment]
Cool :) 

Update: I successfully froze it into a windows binary, and added a web front end as well (`web_export.py`) for a friend who's a Mac user.

Not the neatest code I've written but it works...

**Comment by mdavis-xyz** [comment]
I just added those changes.

I tried `export_gui.py`. That worked.

I couldn't get `export_web.py` working on my Linux machine. Does that *only* work on Mac?

**Comment by phlummox** [comment]
Hm, no, should work anywhere, I think. I'll try running it under a fresh Docker linux image and see if there's some prerequisite I've forgotten to mention. Do you happen to have the error message/stack trace the web script failed with?

**Comment by mdavis-xyz** [comment]
This is what I see on my Ubuntu laptop, with the virtual env activated, when running `python export_web.py`.

```
matthew@kira:~/Documents/Projects/Pandora$ . ./env/bin/activate
(env) matthew@kira:~/Documents/Projects/Pandora$ python export_web.py 
server started - :8080
bad req /rest/system/error
127.0.0.1 - - [25/Jul/2017 19:43:28] "GET /rest/system/error HTTP/1.0" 404 -
bad req /rest/system/status
127.0.0.1 - - [25/Jul/2017 19:43:28] "GET /rest/system/status HTTP/1.0" 404 -
bad req /rest/system/connections
127.0.0.1 - - [25/Jul/2017 19:43:28] "GET /rest/system/connections HTTP/1.0" 404 -
bad req /rest/system/error
127.0.0.1 - - [25/Jul/2017 19:43:29] "GET /rest/system/error HTTP/1.0" 404 -
bad req /rest/system/status
127.0.0.1 - - [25/Jul/2017 19:43:29] "GET /rest/system/status HTTP/1.0" 404 -
bad req /rest/system/connections
127.0.0.1 - - [25/Jul/2017 19:43:29] "GET /rest/system/connections HTTP/1.0" 404 -
bad req /rest/system/error
127.0.0.1 - - [25/Jul/2017 19:43:30] "GET /rest/system/error HTTP/1.0" 404 -
bad req /rest/system/status
127.0.0.1 - - [25/Jul/2017 19:43:30] "GET /rest/system/status HTTP/1.0" 404 -
bad req /rest/system/connections
127.0.0.1 - - [25/Jul/2017 19:43:30] "GET /rest/system/connections HTTP/1.0" 404 -
bad req /rest/system/error
127.0.0.1 - - [25/Jul/2017 19:43:31] "GET /rest/system/error HTTP/1.0" 404 -
bad req /rest/system/status
127.0.0.1 - - [25/Jul/2017 19:43:31] "GET /rest/system/status HTTP/1.0" 404 -
bad req /rest/system/connections
127.0.0.1 - - [25/Jul/2017 19:43:31] "GET /rest/system/connections HTTP/1.0" 404 -
bad req /rest/system/error
127.0.0.1 - - [25/Jul/2017 19:43:32] "GET /rest/system/error HTTP/1.0" 404 -
bad req /rest/system/status
127.0.0.1 - - [25/Jul/2017 19:43:32] "GET /rest/system/status HTTP/1.0" 404 -
bad req /rest/system/connections
127.0.0.1 - - [25/Jul/2017 19:43:32] "GET /rest/system/connections HTTP/1.0" 404 -
bad req /rest/system/error
127.0.0.1 - - [25/Jul/2017 19:43:33] "GET /rest/system/error HTTP/1.0" 404 -
bad req /rest/system/status
127.0.0.1 - - [25/Jul/2017 19:43:33] "GET /rest/system/status HTTP/1.0" 404 -
bad req /rest/system/connections
127.0.0.1 - - [25/Jul/2017 19:43:33] "GET /rest/system/connections HTTP/1.0" 404 -
```

**Comment by phlummox** [comment]
Huh, that's an interesting one! Looks like something may have changed in a Python HTTP library. Will try to reproduce. Cheers!

**Comment by phlummox** [comment]
Hi Matthew, I don't seem to be able to reproduce the problem, unfortunately. I've spun up fresh Alpine linux & Ubuntu Xenial containers in docker, and it seems to run perfectly (docker files attached, if you want to try: 
[docker.tar.gz](https://github.com/mlda065/Pandora-Export/files/1173919/docker.tar.gz) ).

Looking at the log you provided, it appears as if some totally unrelated application is trying to make HTTP requests to a RESTful HTTP API on the same port the server is serving on. Googling for "`/rest/system/connections`", a client trying to query the [Syncthing](https://syncthing.net/) REST API seems a likely suspect - might you have programs running on any of your computers that use Syncthing, or [pysyncthing](https://pypkg.com/pypi/pysyncthing/), and could be trying to query the port you were serving on?

If it's not that, then I'm not sure what the problem could be; but I'm pleased to hear that at least the Tkinter GUI worked.

**Comment by mdavis-xyz** [comment]
Ah yes, I use Syncthing. I'll try with a different port number.

**Comment by mdavis-xyz** [comment]
Yep, a different port number fixed it.

Also I didn't actually add the files in my previous commit. Woops.

Apparently the `-a` in  `git add -a -m 'blah'` doesn't do what I thought it did.

**Comment by phlummox** [comment]
Awesome - glad it all worked :) \*nods* I find git commands often don't do what I think they do. I will confess I largely use [`hg-git`](http://hg-git.github.io/) so that I can work on git repos from mercurial, and avoid having to deal with git ;)
